apply plugin: 'com.android.application'

android {
    compileSdk 32

    defaultConfig {
        applicationId "net.bancer.sparkdict"
        minSdkVersion 30
        targetSdk 31
        versionCode 7
        versionName "1.2.0"
        testApplicationId "net.bancer.sparkdict.test"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            enableAndroidTestCoverage true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
    namespace 'net.bancer.sparkdict'
    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation files('libs/commons-compress-1.5.jar')
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    androidTestImplementation 'androidx.test.espresso:espresso-intents:3.6.1'
}
